/**
 * Traffic obfuscation layer for the panel↔node channel.
 *
 * Goal: make the daemon's API traffic look like ordinary HTTPS/WebSocket
 * traffic to DPI systems and bypass whitelist-based filtering.
 *
 * Technique:
 *   1. All API traffic runs over TLS (HTTPS/WSS) — already looks like web traffic.
 *   2. The WebSocket upgrade path is disguised as a CDN-style path (/cdn-cgi/ws)
 *      rather than /exec/ or /stats/, which are obvious daemon signatures.
 *   3. WebSocket frames are XOR-obfuscated with a rotating session key derived
 *      from the daemon key via HKDF. This breaks protocol fingerprinting that
 *      looks at frame content patterns.
 *   4. Random padding bytes are injected into frames to defeat length-based
 *      traffic analysis.
 *   5. HTTP responses include fake CDN headers (CF-Ray, X-Cache) to blend with
 *      Cloudflare-proxied traffic patterns.
 *
 * The panel must use the ObfuscatedWebSocket client (see docs/API.md) which
 * applies the same XOR+padding in reverse.
 *
 * This is NOT encryption — TLS handles that. This is obfuscation to defeat
 * DPI pattern matching on top of the encrypted channel.
 */

const crypto = require('crypto');
const WebSocket = require('ws');
const CatLoggr  = require('cat-loggr');

const log = new CatLoggr();

// ── Key derivation ────────────────────────────────────────────────────────────

/**
 * Derive a per-session obfuscation key from the daemon key and a random nonce.
 * Uses HKDF-SHA256 so the obfuscation key is independent of the auth key.
 */
function deriveObfuscationKey(daemonKey, nonce) {
    return crypto.hkdfSync(
        'sha256',
        Buffer.from(daemonKey, 'utf8'),
        nonce,                          // salt = session nonce
        Buffer.from('lunarix-obfs-v1'), // info
        32                              // 256-bit key
    );
}

// ── Frame codec ───────────────────────────────────────────────────────────────

const MAX_PADDING = 64; // max random padding bytes per frame

/**
 * Encode a plaintext buffer into an obfuscated frame:
 *
 *   [1 byte: padding length N] [N random bytes] [XOR(payload, key)]
 *
 * The XOR key stream is generated by cycling through the 32-byte session key.
 */
function encodeFrame(plaintext, sessionKey) {
    const paddingLen = crypto.randomInt(0, MAX_PADDING + 1);
    const padding    = crypto.randomBytes(paddingLen);

    const xored = Buffer.alloc(plaintext.length);
    for (let i = 0; i < plaintext.length; i++) {
        xored[i] = plaintext[i] ^ sessionKey[i % sessionKey.length];
    }

    return Buffer.concat([
        Buffer.from([paddingLen]),
        padding,
        xored,
    ]);
}

/**
 * Decode an obfuscated frame back to plaintext.
 */
function decodeFrame(frame, sessionKey) {
    if (frame.length < 1) throw new Error('Frame too short');
    const paddingLen = frame[0];
    if (frame.length < 1 + paddingLen) throw new Error('Frame truncated');

    const xored = frame.slice(1 + paddingLen);
    const plain = Buffer.alloc(xored.length);
    for (let i = 0; i < xored.length; i++) {
        plain[i] = xored[i] ^ sessionKey[i % sessionKey.length];
    }
    return plain;
}

// ── Fake CDN headers middleware ───────────────────────────────────────────────

/**
 * Express middleware that adds fake Cloudflare-style headers to all responses.
 * DPI systems that whitelist Cloudflare traffic will see these and pass through.
 */
function fakeCdnHeaders(req, res, next) {
    // Fake CF-Ray: 16 hex chars + datacenter code
    const ray = crypto.randomBytes(8).toString('hex') + '-AMS';
    res.setHeader('CF-Ray',        ray);
    res.setHeader('CF-Cache-Status', 'DYNAMIC');
    res.setHeader('X-Cache',       'Miss from cloudflare');
    res.setHeader('Server',        'cloudflare');
    res.setHeader('Alt-Svc',       'h3=":443"; ma=86400');
    next();
}

// ── Obfuscated WebSocket server ───────────────────────────────────────────────

/**
 * Wraps a standard WebSocket server with the obfuscation codec.
 *
 * The handshake protocol:
 *   1. Client connects to /cdn-cgi/ws/<realPath> (disguised URL)
 *   2. Server sends: {"event":"nonce","nonce":"<32-byte hex>"}
 *   3. Client derives session key = HKDF(daemonKey, nonce)
 *   4. All subsequent frames are encoded/decoded with encodeFrame/decodeFrame
 *   5. The real auth {"event":"auth","args":["<key>"]} is sent inside the
 *      obfuscated channel, so the key never appears in plaintext frames
 *
 * @param {http.Server|https.Server} server
 * @param {string} daemonKey
 * @param {Function} onConnection(ws, req, realPath) — called with a transparent ws
 */
function createObfuscatedWss(server, daemonKey, onConnection) {
    // Mount on the disguised path
    const wss = new WebSocket.Server({ server, path: '/cdn-cgi/ws' });

    wss.on('connection', (rawWs, req) => {
        // Extract the real path from the query string: ?p=/exec/abc123
        const url      = new URL(req.url, 'https://localhost');
        const realPath = url.searchParams.get('p') || '/';

        // Generate a per-session nonce and derive the obfuscation key
        const nonce      = crypto.randomBytes(32);
        const sessionKey = deriveObfuscationKey(daemonKey, nonce);

        // Send nonce to client so it can derive the same key
        rawWs.send(JSON.stringify({ event: 'nonce', nonce: nonce.toString('hex') }));

        // Create a transparent wrapper that the rest of the daemon talks to
        const transparentWs = createTransparentWrapper(rawWs, sessionKey, realPath, req);

        onConnection(transparentWs, req, realPath);
    });

    return wss;
}

/**
 * Creates an EventEmitter that looks like a WebSocket to the daemon internals,
 * but transparently encodes/decodes frames through the obfuscation layer.
 */
function createTransparentWrapper(rawWs, sessionKey, realPath, req) {
    const { EventEmitter } = require('events');
    const wrapper = new EventEmitter();

    // Mimic WebSocket interface
    wrapper.readyState = rawWs.readyState;

    wrapper.send = (data) => {
        if (rawWs.readyState !== WebSocket.OPEN) return;
        try {
            const plain  = Buffer.isBuffer(data) ? data : Buffer.from(String(data));
            const frame  = encodeFrame(plain, sessionKey);
            rawWs.send(frame);
        } catch (err) {
            log.error('Obfs encode error:', err.message);
        }
    };

    wrapper.close = (code, reason) => rawWs.close(code, reason);

    // Decode incoming frames and re-emit as 'message'
    rawWs.on('message', (frame) => {
        try {
            const plain = decodeFrame(Buffer.isBuffer(frame) ? frame : Buffer.from(frame), sessionKey);
            wrapper.readyState = rawWs.readyState;
            wrapper.emit('message', plain);
        } catch (err) {
            log.warn('Obfs decode error (bad frame):', err.message);
            rawWs.close(1002, 'Bad frame');
        }
    });

    rawWs.on('close',   (code, reason) => { wrapper.readyState = WebSocket.CLOSED; wrapper.emit('close', code, reason); });
    rawWs.on('error',   (err)          => wrapper.emit('error', err));
    rawWs.on('open',    ()             => { wrapper.readyState = WebSocket.OPEN; wrapper.emit('open'); });

    // Expose the real path so the daemon can route correctly
    wrapper._realPath = realPath;

    return wrapper;
}

// ── Xray/Sing-box sidecar config generator ────────────────────────────────────

/**
 * Generates a Xray-core config for a container sidecar.
 *
 * The sidecar runs as a Docker container alongside the game server.
 * It accepts the game protocol on a local port and forwards it through
 * a VLESS+WS+TLS tunnel, making the game traffic look like HTTPS to DPI.
 *
 * @param {object} opts
 * @param {string} opts.uuid          — VLESS user UUID
 * @param {string} opts.serverAddr    — remote Xray server address
 * @param {number} opts.serverPort    — remote Xray server port (443)
 * @param {string} opts.wsPath        — WebSocket path on the server (e.g. /cdn-cgi/game)
 * @param {string} opts.sni           — TLS SNI (domain to impersonate)
 * @param {number} opts.localPort     — local port to accept game traffic on
 * @param {string} opts.protocol      — 'tcp' or 'udp'
 */
function generateXrayConfig(opts) {
    const { uuid, serverAddr, serverPort, wsPath, sni, localPort, protocol = 'tcp' } = opts;

    return {
        log: { loglevel: 'warning' },
        inbounds: [{
            port:     localPort,
            protocol: 'dokodemo-door',
            settings: {
                network:    protocol,
                followRedirect: false,
            },
            tag: 'game-in',
        }],
        outbounds: [{
            protocol: 'vless',
            settings: {
                vnext: [{
                    address: serverAddr,
                    port:    serverPort,
                    users:   [{ id: uuid, encryption: 'none', flow: '' }],
                }],
            },
            streamSettings: {
                network:     'ws',
                security:    'tls',
                tlsSettings: {
                    serverName:         sni,
                    allowInsecure:      false,
                    fingerprint:        'chrome', // TLS fingerprint mimics Chrome
                },
                wsSettings: {
                    path:    wsPath,
                    headers: { Host: sni },
                },
            },
            tag: 'vless-out',
        }, {
            protocol: 'freedom',
            tag:      'direct',
        }],
        routing: {
            rules: [{
                type:        'field',
                inboundTag:  ['game-in'],
                outboundTag: 'vless-out',
            }],
        },
    };
}

module.exports = {
    fakeCdnHeaders,
    createObfuscatedWss,
    encodeFrame,
    decodeFrame,
    deriveObfuscationKey,
    generateXrayConfig,
};
